# Generated by Django 4.1.7 on 2023-02-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
