# Generated by Django 4.1.7 on 2023-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_category_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('MC', 'Microcosm'), ('QOTD', 'Quote of the Day'), ('I_D', 'Inter-dimensional'), ('Q_D', 'Quasi-dimensional')], default='MC', max_length=255, null=True),
        ),
    ]
