# Generated by Django 4.1.7 on 2023-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_is_archived_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('published', 'published'), ('submitted', 'submitted'), ('archived', 'archived'), ('draft', 'draft')], default='draft', max_length=255, null=True),
        ),
    ]
