# Generated by Django 4.1.7 on 2023-03-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Microcosm', 'Microcosm'), ('Quote of the Day', 'Quote of the Day'), ('Inter-dimensional', 'Inter-dimensional'), ('Quasi-dimensional', 'Quasi-dimensional')], default='Microcosm', max_length=255, null=True),
        ),
    ]
